---

- name: Configure BGP router with neighbors
  ios_config:
    provider: '{{ rtr_auth }}'
    lines: 
      - neighbor {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }} remote-as {{ bgp_myas }}
    parents: router bgp {{ bgp_router_as }}
  with_items:
    - "{{ groups['master'] }}"
    - "{{ groups['worker'] }}"
