---
# This playbook installs two sample applications with contiv security groups and istio sidecars.

- name: Deploy Sample Applications
  hosts: master
  remote_user: "{{ ansible_remote_user }}"
  become: yes
  become_method: sudo
  roles:
    - { role: sample_apps, when: deploy_sample_apps }