---
- name: Copy WordPressSQL YAML to host
  template:
    src: wordpresssql.yaml
    dest: /tmp/wordpresssql.yaml


- name: Create SQL Secret
  command: "kubectl --kubeconfig /etc/kubernetes/admin.conf create secret generic mysql-pass --from-literal=password=YOUR_PASSWORD"

- name: Deploying Wordpress SQL
  command: "kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f /tmp/wordpresssql.yaml"

