---

- name: install docker
  apt: package={{ item }} update_cache=yes
  with_items:
    - docker.io

- name: add remote user to group docker
  command: usermod -aG docker {{ansible_user}}

- name: Start docker service
  service:
    name: docker
    state: restarted
    enabled: yes